Repository bookmebus/spree_vpago, pull requests merged in 2021-02, with the labels that each got.

#7 Close #5 create payment source and update order status
  app/controllers/spree/checkout_controller_decorator.rb
  app/controllers/spree/webhook/base_controller.rb
  app/controllers/spree/webhook/payways_controller.rb
  app/models/spree/gateway/payway.rb
  app/models/spree/vpago_payment_source.rb
  app/models/vpago/order_decorator.rb
  app/models/vpago/payment/payway_processing_decorator.rb
  app/models/vpago/payment_decorator.rb
  app/views/spree/checkout/payment/_payment_abapay.html.erb
  app/views/spree/checkout/payment/_payment_cards.html.erb
  app/views/spree/checkout/payment/_payment_payway.html.erb
  app/views/spree/checkout/payment/payway_form.html.erb
  config/routes.rb
  db/migrate/20210128040625_create_spree_vpago_payment_sources.rb
  lib/spree_vpago/engine.rb
  lib/vpago/payway/base.rb
  lib/vpago/payway/checkout.rb
  lib/vpago/payway/payment_status_updater.rb
  lib/vpago/payway/transaction_status.rb
  spec/controllers/spree/webhook/payways_controller_spec.rb
  spec/factories/payway_gateways.rb
  spec/factories/payway_payment_sources.rb
  spec/factories/payway_payments.rb
  spec/lib/vpago/payway/base_spec.rb
  spec/lib/vpago/payway/checkout_spec.php
  spec/lib/vpago/payway/checkout_spec.rb
  spec/lib/vpago/payway/payment_status_updater_spec.rb
  spec/models/spree/gateway/payway_spec.rb
  spree_vpago.gemspec
Labels: good first issue

#8 6 support dynamic host between production and staging
  app/models/spree/gateway/payway.rb
  app/views/spree/checkout/payment/_payway_loader.html.erb
  app/views/spree/checkout/payment/_payway_root.html.erb
  app/views/spree/checkout/payment/_payway_script.html.erb
  app/views/spree/checkout/payment/payway_form.html.erb
  lib/vpago/payway/base.rb
Labels: good first issue

#10 Close #9 Fix incorrect value returned by url method in transaction st…
  lib/vpago/payway/transaction_status.rb
  spec/lib/vpago/payway/transaction_status_spec.rb
Labels: bug, enhancement

#12 Close #11 cancel action in payment
  app/models/spree/gateway/payway.rb
  spec/models/spree/order_spec.rb
Labels: duplicate

#15 Close #13 handle missing email for payment info
  README.md
  lib/vpago/payway/base.rb
Labels: documentation
