Repository bookmebus/spree_vpago, pull requests merged in 2024-08, with the labels that each got.

#177 close #176 add order channel to success url
  lib/vpago/acleda/base.rb
  lib/vpago/payway_v2/base.rb
  spec/lib/vpago/acleda/checkout_spec.rb
  spec/lib/vpago/payway_v2/base_spec.rb
Labels: enhancement

#179 close #178 allow vendor to have their own payment methods
  app/controllers/spree/admin/payment_methods_controller_decorator.rb
  app/models/vpago/line_item_decorator.rb
  app/models/vpago/order_decorator.rb
  app/models/vpago/payment_method_decorator.rb
  app/models/vpago/store_decorator.rb
  app/models/vpago/variant_decorator.rb
  app/models/vpago/vendor_decorator.rb
  app/overrides/spree/admin/payment_methods/_form/vendor_field.html.erb.deface
  app/overrides/spree/admin/payment_methods/index/payment_methods_tabs.html.erb.deface
  app/overrides/spree/admin/payment_methods/index/vendor_body.html.erb.deface
  app/overrides/spree/admin/payment_methods/index/vendor_header.html.erb.deface
  app/views/spree/admin/shared/_payment_methods_tabs.html.erb
  db/migrate/20240808102853_add_vendor_reference_to_spree_payment_methods.rb
  lib/generators/spree_vpago/install/install_generator.rb
  spec/models/spree/order_spec.rb
Labels: feature

#181 close #180 only generate payout when validate
  app/models/vpago/payouts_generator.rb
  spec/models/vpago/payouts_generator_spec.rb
Labels: enhancement

#183 close #182 add return deeplink
  app/models/spree/gateway/payway_v2.rb
  lib/vpago/payway_v2/base.rb
  lib/vpago/payway_v2/checkout.rb
  spec/lib/vpago/payway_v2/base_spec.rb
  spec/lib/vpago/payway_v2/payouts_params_constructor_spec.rb
Labels: enhancement

#186 close #185 add abapay_khqr_deeplink
  app/services/vpago/payment_redirect_handler.rb
  lib/vpago/payway.rb
  lib/vpago/payway_v2/base.rb
  spec/lib/vpago/payway_spec.rb
  spec/lib/vpago/payway_v2/base_spec.rb
  spec/services/vpago/payment_redirect_handler_spec.rb
Labels: feature

#188 close #187 allow frontend to pass return_deeplink_url
  app/controllers/spree/api/v2/storefront/checkout_controller_decorator.rb
  app/services/vpago/payment_redirect_handler.rb
  lib/vpago/payway_v2/base.rb
  spec/lib/vpago/payway_v2/base_spec.rb
Labels: enhancement

#190 close #189 filter vendor payment methods by ticket seller role
  app/models/vpago/order_decorator.rb
  spec/models/spree/order_spec.rb
Labels: backend
