Repository bookmebus/spree_vpago, pull requests merged in 2025-03, with the labels that each got.

#246 Close #245 build and publish gem
  .github/workflows/test_and_publish_gem.yml
  .gitignore
  README.md
  db/migrate/20210430052432_add_fields_to_payment_sources.rb
  lib/spree_vpago/version.rb
  spree_vpago.gemspec
Labels: enhancement

#248 close #247 fix return request from ABA failed
  app/controllers/spree/vpago_payments_controller.rb
  spec/controllers/spree/vpago_payments_controller_spec.rb
Labels: enhancement

#244 close #243 use order created_at for segment data instead of current date
  app/assets/javascripts/vpago/vpago_payments/user_informers/firebase.js
  app/javascripts/vpago/vpago_payments/user_informers/firebase.js
  app/models/vpago/payment_decorator.rb
  app/serializers/spree/v2/storefront/payment_serializer_decorator.rb
  app/services/vpago/user_informers/firebase.rb
  app/views/spree/vpago_payments/processing.html.erb
  spec/services/vpago/user_informers/firebase_spec.rb
Labels: enhancement

#251 close #250 add more details message & log during processing payment
  Gemfile.lock
  app/assets/javascripts/vpago/vpago_payments/user_informers/firebase.js
  app/javascripts/queue_processor.js
  app/javascripts/queue_processor.test.js
  app/javascripts/vpago/vpago_payments/user_informers/firebase.js
  app/models/vpago/payment_decorator.rb
  app/services/vpago/payment_processable.rb
  app/services/vpago/payment_processor.rb
  app/services/vpago/user_informers/firebase.rb
  app/views/spree/vpago_payments/processing.html.erb
  lib/vpago/payway_v2/base.rb
  package.json
  spec/models/spree/payment_spec.rb
  spec/services/vpago/payment_processor_spec.rb
  spec/services/vpago/user_informers/firebase_spec.rb
  spec/spec_helper.rb
  yarn.lock
Labels: enhancement

#254 close #252 scope tenant payment method
  app/controllers/spree/admin/payment_methods_controller_decorator.rb
  app/overrides/spree/admin/payment_methods/index/payment_methods_tabs.html.erb.deface
  app/overrides/spree/admin/payment_methods/index/tenant_body.html.erb.deface
  app/overrides/spree/admin/payment_methods/index/tenant_header.html.erb.deface
  app/views/spree/admin/shared/_payment_methods_tabs.html.erb
Labels: api, backend

#258 close #257 fetch available tenant payment_methods of order
  app/models/vpago/order_decorator.rb
Labels: api
